# Header
subtitle: 记录 交流 进步
menu:
  主页: /
  所有文章: /archives
  #算法: /tags/数据结构与算法
  #机器学习: /tags/机器学习算法
  python: /tags/python
  #杂谈: /tags/杂谈
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/zhanghu798"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "zhanghu798@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /assets/blogImg/zhanghu798.jpg

#你的头像url
avatar: /assets/blogImg/zhanghu798.jpg
#是否开启分享
share_jia: true
share_addthis: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "zhanghu798"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends: False 

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 张虎,13年毕业于兰州交通大学应用物理专业,2年软件开发经验,对数据分析和数据挖掘感兴趣
